name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0.x
      id: setup-dotnet6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 3.1.x
      id: setup-dotnet3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      id: restore-deps
      run: dotnet restore ./src/Vlingo.Xoom.Actors.sln
    - name: Build
      id: build
      run: dotnet build ./src/Vlingo.Xoom.Actors.sln --no-restore
    - name: Test
      id: test
      run: dotnet test ./src/Vlingo.Xoom.Actors.Tests/Vlingo.Xoom.Actors.Tests.csproj --no-build --verbosity normal
    - name: slack - GitHub Actions Slack integration
      uses: act10ns/slack@v1.2.2
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()